environment:
  SEED: 0
  NUM_AGENTS: 1
  # TRACK
  TRACK_LEN: 5.0
  # LOOP: true
  TIMEOUT: 100
  # DONE FLAG PARAM
  END_CRITERION: failure
  G_X_FAIL: 0.0
  OBSC_TYPE: circle
  OBS_SPEC:
    - [2.5, 0.0, 0.25]
    - [4.5, 0.0, 0.2]
  #  - [6.5, 0.0, 0.2]
  #  - [8.5, 0.7, 0.25]
  #  - [8.5, -0.7, 0.25]
  #  - [11.0, 0.1, 0.35]
  RESET_SPACE:
    - [0., 8.0]
    - [-0.4, 0.4]
    - [0.5, 1.5]
    - [-0.3, 0.3]
    - [-0.15, 0.15]

cost:
  # Task policy tuned weights
  WT_ACCEL: 0.01
  WT_OMEGA: 0.01
  W_TRACK: 0.01
  W_VEL: 0.01
  YAWT_MIN: -1.2
  YAWT_MAX: 1.2
  V_REF: 0.9
  VT_MIN: 0.0
  VT_MAX: 2.0
  Q1_V: 0.1
  Q2_V: 0.1
  Q1_YAW: 0.1
  Q2_YAW: 0.1
  BARRIER_CLIP_MIN: -0.25
  BARRIER_CLIP_MAX: 5.0
  
  # Safety DDP parameters
  USE_YAW: false
  USE_VEL: false
  USE_DELTA: false
  COST_TYPE: Reachavoid
  # SAFETY COST PARAM
  W_ACCEL: 0.0001
  W_OMEGA: 0.0001
  YAW_MIN: -1.57
  YAW_MAX: 1.57

agent:
  AGENT_ID: ego
  DYN: Bicycle5D
  FOOTPRINT: Circle
  EGO_RADIUS: 0.1
  ACTION_RANGE:
    - [-0.5, 0.5]
    - [-0.8, 0.8]
  WEIGHT : 2.99  # kg
  # CAR DYNAMICS
  WHEELBASE: 0.2
  DT: 0.05
  DELTA_MIN: -1.2  # ra
  DELTA_MAX: 1.2
  #VMIN should be zero
  V_MIN: 0.0
  V_MAX: 2.0

solver:
  INIT_STATE: [0.0, 0.0, 0.6, 0.0, 0.0]
  N: 45
  MAX_ITER: 20
  MAX_ITER_RECEDING: 270
  # Line search options: 'baseline'.
  LINE_SEARCH: 'baseline'
  # Shielding options: 'none', 'LR', 'CBF'
  FILTER_TYPE: 'CBF'
  CBF_TYPE: 'quadratic'
  BARRIER_GAMMA: 0.9
  LR_THRESHOLD: 0.0
  OUT_FOLDER: exps_may/ilqr/bic5D/reachavoid_yaw_experiment_config_gp/
  DEVICE: cpu
  FIG_SIZE_X: 8
  FIG_SIZE_Y: 2.5
  FRAME_SKIP: 2